export default [
  'backbone'
  'backbone-validation'
  'backbone.marionette'
  'backbone.paginator'
  'backbone.radio'
  'backbone.routefilter'
  'bootstrap'
  'jquery'
  'marionette.toolkit'
  'marked'
  'ms'
  'popper.js'
  'teacup'
  'underscore'
  ]
